# Generated by Django 3.1.7 on 2021-04-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.myuser')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.PositiveIntegerField()),
                ('citizenship_number', models.PositiveIntegerField()),
                ('citizenship_front', models.ImageField(upload_to='')),
                ('citizenship_back', models.ImageField(upload_to='')),
                ('temp_add', models.CharField(max_length=50)),
                ('per_add', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
