# Generated by Django 3.1.7 on 2021-04-08 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_profile.shopprofile')),
            ],
        ),
    ]
